/**
 * generated by Xtext 2.21.0
 */
package io.vertigo.dsl.vertigoDsl.impl;

import io.vertigo.dsl.vertigoDsl.DtDefinitionStaticValues;
import io.vertigo.dsl.vertigoDsl.VertigoDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dt Definition Static Values</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.impl.DtDefinitionStaticValuesImpl#getHandleField <em>Handle Field</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DtDefinitionStaticValuesImpl extends MinimalEObjectImpl.Container implements DtDefinitionStaticValues
{
  /**
   * The default value of the '{@link #getHandleField() <em>Handle Field</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHandleField()
   * @generated
   * @ordered
   */
  protected static final String HANDLE_FIELD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHandleField() <em>Handle Field</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHandleField()
   * @generated
   * @ordered
   */
  protected String handleField = HANDLE_FIELD_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DtDefinitionStaticValuesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VertigoDslPackage.Literals.DT_DEFINITION_STATIC_VALUES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHandleField()
  {
    return handleField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHandleField(String newHandleField)
  {
    String oldHandleField = handleField;
    handleField = newHandleField;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VertigoDslPackage.DT_DEFINITION_STATIC_VALUES__HANDLE_FIELD, oldHandleField, handleField));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VertigoDslPackage.DT_DEFINITION_STATIC_VALUES__HANDLE_FIELD:
        return getHandleField();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VertigoDslPackage.DT_DEFINITION_STATIC_VALUES__HANDLE_FIELD:
        setHandleField((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VertigoDslPackage.DT_DEFINITION_STATIC_VALUES__HANDLE_FIELD:
        setHandleField(HANDLE_FIELD_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VertigoDslPackage.DT_DEFINITION_STATIC_VALUES__HANDLE_FIELD:
        return HANDLE_FIELD_EDEFAULT == null ? handleField != null : !HANDLE_FIELD_EDEFAULT.equals(handleField);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (handleField: ");
    result.append(handleField);
    result.append(')');
    return result.toString();
  }

} //DtDefinitionStaticValuesImpl
