/**
 * generated by Xtext 2.21.0
 */
package io.vertigo.dsl.vertigoDsl.impl;

import io.vertigo.dsl.vertigoDsl.FacetDefinition;
import io.vertigo.dsl.vertigoDsl.FacetedQueryDefinitionFacets;
import io.vertigo.dsl.vertigoDsl.VertigoDslPackage;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Faceted Query Definition Facets</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.impl.FacetedQueryDefinitionFacetsImpl#getFacetDefinition <em>Facet Definition</em>}</li>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.impl.FacetedQueryDefinitionFacetsImpl#getFacets <em>Facets</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FacetedQueryDefinitionFacetsImpl extends MinimalEObjectImpl.Container implements FacetedQueryDefinitionFacets
{
  /**
   * The cached value of the '{@link #getFacetDefinition() <em>Facet Definition</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFacetDefinition()
   * @generated
   * @ordered
   */
  protected EList<FacetDefinition> facetDefinition;

  /**
   * The cached value of the '{@link #getFacets() <em>Facets</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFacets()
   * @generated
   * @ordered
   */
  protected EList<FacetDefinition> facets;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FacetedQueryDefinitionFacetsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VertigoDslPackage.Literals.FACETED_QUERY_DEFINITION_FACETS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<FacetDefinition> getFacetDefinition()
  {
    if (facetDefinition == null)
    {
      facetDefinition = new EObjectResolvingEList<FacetDefinition>(FacetDefinition.class, this, VertigoDslPackage.FACETED_QUERY_DEFINITION_FACETS__FACET_DEFINITION);
    }
    return facetDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<FacetDefinition> getFacets()
  {
    if (facets == null)
    {
      facets = new EObjectResolvingEList<FacetDefinition>(FacetDefinition.class, this, VertigoDslPackage.FACETED_QUERY_DEFINITION_FACETS__FACETS);
    }
    return facets;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_FACETS__FACET_DEFINITION:
        return getFacetDefinition();
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_FACETS__FACETS:
        return getFacets();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_FACETS__FACET_DEFINITION:
        getFacetDefinition().clear();
        getFacetDefinition().addAll((Collection<? extends FacetDefinition>)newValue);
        return;
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_FACETS__FACETS:
        getFacets().clear();
        getFacets().addAll((Collection<? extends FacetDefinition>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_FACETS__FACET_DEFINITION:
        getFacetDefinition().clear();
        return;
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_FACETS__FACETS:
        getFacets().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_FACETS__FACET_DEFINITION:
        return facetDefinition != null && !facetDefinition.isEmpty();
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_FACETS__FACETS:
        return facets != null && !facets.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //FacetedQueryDefinitionFacetsImpl
