/**
 * generated by Xtext 2.18.0
 */
package io.vertigo.dsl.vertigoDsl.impl;

import io.vertigo.dsl.vertigoDsl.IndexDefinition;
import io.vertigo.dsl.vertigoDsl.VertigoDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Index Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IndexDefinitionImpl extends ElementImpl implements IndexDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IndexDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VertigoDslPackage.Literals.INDEX_DEFINITION;
  }

} //IndexDefinitionImpl
