/**
 * generated by Xtext 2.23.0
 */
package io.vertigo.dsl.vertigoDsl.impl;

import io.vertigo.dsl.vertigoDsl.IndexDefinitionAction;
import io.vertigo.dsl.vertigoDsl.IndexDefinitionDtIndex;
import io.vertigo.dsl.vertigoDsl.IndexDefinitionIndexCopyTo;
import io.vertigo.dsl.vertigoDsl.IndexDefinitionKeyConcept;
import io.vertigo.dsl.vertigoDsl.IndexDefinitionLoaderId;
import io.vertigo.dsl.vertigoDsl.VertigoDslPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Index Definition Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.impl.IndexDefinitionActionImpl#getName <em>Name</em>}</li>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.impl.IndexDefinitionActionImpl#getIndexDefinitionKeyConcept <em>Index Definition Key Concept</em>}</li>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.impl.IndexDefinitionActionImpl#getIndexDefinitionDtIndex <em>Index Definition Dt Index</em>}</li>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.impl.IndexDefinitionActionImpl#getIndexDefinitionLoaderId <em>Index Definition Loader Id</em>}</li>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.impl.IndexDefinitionActionImpl#getIndexDefinitionIndexCopyTo <em>Index Definition Index Copy To</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IndexDefinitionActionImpl extends IndexDefinitionImpl implements IndexDefinitionAction
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getIndexDefinitionKeyConcept() <em>Index Definition Key Concept</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIndexDefinitionKeyConcept()
   * @generated
   * @ordered
   */
  protected IndexDefinitionKeyConcept indexDefinitionKeyConcept;

  /**
   * The cached value of the '{@link #getIndexDefinitionDtIndex() <em>Index Definition Dt Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIndexDefinitionDtIndex()
   * @generated
   * @ordered
   */
  protected IndexDefinitionDtIndex indexDefinitionDtIndex;

  /**
   * The cached value of the '{@link #getIndexDefinitionLoaderId() <em>Index Definition Loader Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIndexDefinitionLoaderId()
   * @generated
   * @ordered
   */
  protected IndexDefinitionLoaderId indexDefinitionLoaderId;

  /**
   * The cached value of the '{@link #getIndexDefinitionIndexCopyTo() <em>Index Definition Index Copy To</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIndexDefinitionIndexCopyTo()
   * @generated
   * @ordered
   */
  protected IndexDefinitionIndexCopyTo indexDefinitionIndexCopyTo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IndexDefinitionActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VertigoDslPackage.Literals.INDEX_DEFINITION_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VertigoDslPackage.INDEX_DEFINITION_ACTION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IndexDefinitionKeyConcept getIndexDefinitionKeyConcept()
  {
    return indexDefinitionKeyConcept;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIndexDefinitionKeyConcept(IndexDefinitionKeyConcept newIndexDefinitionKeyConcept, NotificationChain msgs)
  {
    IndexDefinitionKeyConcept oldIndexDefinitionKeyConcept = indexDefinitionKeyConcept;
    indexDefinitionKeyConcept = newIndexDefinitionKeyConcept;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_KEY_CONCEPT, oldIndexDefinitionKeyConcept, newIndexDefinitionKeyConcept);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIndexDefinitionKeyConcept(IndexDefinitionKeyConcept newIndexDefinitionKeyConcept)
  {
    if (newIndexDefinitionKeyConcept != indexDefinitionKeyConcept)
    {
      NotificationChain msgs = null;
      if (indexDefinitionKeyConcept != null)
        msgs = ((InternalEObject)indexDefinitionKeyConcept).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_KEY_CONCEPT, null, msgs);
      if (newIndexDefinitionKeyConcept != null)
        msgs = ((InternalEObject)newIndexDefinitionKeyConcept).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_KEY_CONCEPT, null, msgs);
      msgs = basicSetIndexDefinitionKeyConcept(newIndexDefinitionKeyConcept, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_KEY_CONCEPT, newIndexDefinitionKeyConcept, newIndexDefinitionKeyConcept));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IndexDefinitionDtIndex getIndexDefinitionDtIndex()
  {
    return indexDefinitionDtIndex;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIndexDefinitionDtIndex(IndexDefinitionDtIndex newIndexDefinitionDtIndex, NotificationChain msgs)
  {
    IndexDefinitionDtIndex oldIndexDefinitionDtIndex = indexDefinitionDtIndex;
    indexDefinitionDtIndex = newIndexDefinitionDtIndex;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_DT_INDEX, oldIndexDefinitionDtIndex, newIndexDefinitionDtIndex);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIndexDefinitionDtIndex(IndexDefinitionDtIndex newIndexDefinitionDtIndex)
  {
    if (newIndexDefinitionDtIndex != indexDefinitionDtIndex)
    {
      NotificationChain msgs = null;
      if (indexDefinitionDtIndex != null)
        msgs = ((InternalEObject)indexDefinitionDtIndex).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_DT_INDEX, null, msgs);
      if (newIndexDefinitionDtIndex != null)
        msgs = ((InternalEObject)newIndexDefinitionDtIndex).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_DT_INDEX, null, msgs);
      msgs = basicSetIndexDefinitionDtIndex(newIndexDefinitionDtIndex, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_DT_INDEX, newIndexDefinitionDtIndex, newIndexDefinitionDtIndex));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IndexDefinitionLoaderId getIndexDefinitionLoaderId()
  {
    return indexDefinitionLoaderId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIndexDefinitionLoaderId(IndexDefinitionLoaderId newIndexDefinitionLoaderId, NotificationChain msgs)
  {
    IndexDefinitionLoaderId oldIndexDefinitionLoaderId = indexDefinitionLoaderId;
    indexDefinitionLoaderId = newIndexDefinitionLoaderId;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_LOADER_ID, oldIndexDefinitionLoaderId, newIndexDefinitionLoaderId);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIndexDefinitionLoaderId(IndexDefinitionLoaderId newIndexDefinitionLoaderId)
  {
    if (newIndexDefinitionLoaderId != indexDefinitionLoaderId)
    {
      NotificationChain msgs = null;
      if (indexDefinitionLoaderId != null)
        msgs = ((InternalEObject)indexDefinitionLoaderId).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_LOADER_ID, null, msgs);
      if (newIndexDefinitionLoaderId != null)
        msgs = ((InternalEObject)newIndexDefinitionLoaderId).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_LOADER_ID, null, msgs);
      msgs = basicSetIndexDefinitionLoaderId(newIndexDefinitionLoaderId, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_LOADER_ID, newIndexDefinitionLoaderId, newIndexDefinitionLoaderId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IndexDefinitionIndexCopyTo getIndexDefinitionIndexCopyTo()
  {
    return indexDefinitionIndexCopyTo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIndexDefinitionIndexCopyTo(IndexDefinitionIndexCopyTo newIndexDefinitionIndexCopyTo, NotificationChain msgs)
  {
    IndexDefinitionIndexCopyTo oldIndexDefinitionIndexCopyTo = indexDefinitionIndexCopyTo;
    indexDefinitionIndexCopyTo = newIndexDefinitionIndexCopyTo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_INDEX_COPY_TO, oldIndexDefinitionIndexCopyTo, newIndexDefinitionIndexCopyTo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIndexDefinitionIndexCopyTo(IndexDefinitionIndexCopyTo newIndexDefinitionIndexCopyTo)
  {
    if (newIndexDefinitionIndexCopyTo != indexDefinitionIndexCopyTo)
    {
      NotificationChain msgs = null;
      if (indexDefinitionIndexCopyTo != null)
        msgs = ((InternalEObject)indexDefinitionIndexCopyTo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_INDEX_COPY_TO, null, msgs);
      if (newIndexDefinitionIndexCopyTo != null)
        msgs = ((InternalEObject)newIndexDefinitionIndexCopyTo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_INDEX_COPY_TO, null, msgs);
      msgs = basicSetIndexDefinitionIndexCopyTo(newIndexDefinitionIndexCopyTo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_INDEX_COPY_TO, newIndexDefinitionIndexCopyTo, newIndexDefinitionIndexCopyTo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_KEY_CONCEPT:
        return basicSetIndexDefinitionKeyConcept(null, msgs);
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_DT_INDEX:
        return basicSetIndexDefinitionDtIndex(null, msgs);
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_LOADER_ID:
        return basicSetIndexDefinitionLoaderId(null, msgs);
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_INDEX_COPY_TO:
        return basicSetIndexDefinitionIndexCopyTo(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__NAME:
        return getName();
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_KEY_CONCEPT:
        return getIndexDefinitionKeyConcept();
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_DT_INDEX:
        return getIndexDefinitionDtIndex();
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_LOADER_ID:
        return getIndexDefinitionLoaderId();
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_INDEX_COPY_TO:
        return getIndexDefinitionIndexCopyTo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__NAME:
        setName((String)newValue);
        return;
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_KEY_CONCEPT:
        setIndexDefinitionKeyConcept((IndexDefinitionKeyConcept)newValue);
        return;
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_DT_INDEX:
        setIndexDefinitionDtIndex((IndexDefinitionDtIndex)newValue);
        return;
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_LOADER_ID:
        setIndexDefinitionLoaderId((IndexDefinitionLoaderId)newValue);
        return;
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_INDEX_COPY_TO:
        setIndexDefinitionIndexCopyTo((IndexDefinitionIndexCopyTo)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_KEY_CONCEPT:
        setIndexDefinitionKeyConcept((IndexDefinitionKeyConcept)null);
        return;
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_DT_INDEX:
        setIndexDefinitionDtIndex((IndexDefinitionDtIndex)null);
        return;
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_LOADER_ID:
        setIndexDefinitionLoaderId((IndexDefinitionLoaderId)null);
        return;
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_INDEX_COPY_TO:
        setIndexDefinitionIndexCopyTo((IndexDefinitionIndexCopyTo)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_KEY_CONCEPT:
        return indexDefinitionKeyConcept != null;
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_DT_INDEX:
        return indexDefinitionDtIndex != null;
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_LOADER_ID:
        return indexDefinitionLoaderId != null;
      case VertigoDslPackage.INDEX_DEFINITION_ACTION__INDEX_DEFINITION_INDEX_COPY_TO:
        return indexDefinitionIndexCopyTo != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //IndexDefinitionActionImpl
