/**
 * generated by Xtext 2.23.0
 */
package io.vertigo.dsl.vertigoDsl.impl;

import io.vertigo.dsl.vertigoDsl.DtDefinitionType;
import io.vertigo.dsl.vertigoDsl.IndexDefinitionKeyConcept;
import io.vertigo.dsl.vertigoDsl.VertigoDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Index Definition Key Concept</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.impl.IndexDefinitionKeyConceptImpl#getDtDefinition <em>Dt Definition</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IndexDefinitionKeyConceptImpl extends MinimalEObjectImpl.Container implements IndexDefinitionKeyConcept
{
  /**
   * The cached value of the '{@link #getDtDefinition() <em>Dt Definition</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDtDefinition()
   * @generated
   * @ordered
   */
  protected DtDefinitionType dtDefinition;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IndexDefinitionKeyConceptImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VertigoDslPackage.Literals.INDEX_DEFINITION_KEY_CONCEPT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionType getDtDefinition()
  {
    if (dtDefinition != null && dtDefinition.eIsProxy())
    {
      InternalEObject oldDtDefinition = (InternalEObject)dtDefinition;
      dtDefinition = (DtDefinitionType)eResolveProxy(oldDtDefinition);
      if (dtDefinition != oldDtDefinition)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, VertigoDslPackage.INDEX_DEFINITION_KEY_CONCEPT__DT_DEFINITION, oldDtDefinition, dtDefinition));
      }
    }
    return dtDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DtDefinitionType basicGetDtDefinition()
  {
    return dtDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDtDefinition(DtDefinitionType newDtDefinition)
  {
    DtDefinitionType oldDtDefinition = dtDefinition;
    dtDefinition = newDtDefinition;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VertigoDslPackage.INDEX_DEFINITION_KEY_CONCEPT__DT_DEFINITION, oldDtDefinition, dtDefinition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VertigoDslPackage.INDEX_DEFINITION_KEY_CONCEPT__DT_DEFINITION:
        if (resolve) return getDtDefinition();
        return basicGetDtDefinition();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VertigoDslPackage.INDEX_DEFINITION_KEY_CONCEPT__DT_DEFINITION:
        setDtDefinition((DtDefinitionType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VertigoDslPackage.INDEX_DEFINITION_KEY_CONCEPT__DT_DEFINITION:
        setDtDefinition((DtDefinitionType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VertigoDslPackage.INDEX_DEFINITION_KEY_CONCEPT__DT_DEFINITION:
        return dtDefinition != null;
    }
    return super.eIsSet(featureID);
  }

} //IndexDefinitionKeyConceptImpl
