/**
 * generated by Xtext 2.21.0
 */
package io.vertigo.dsl.vertigoDsl.impl;

import io.vertigo.dsl.vertigoDsl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class VertigoDslFactoryImpl extends EFactoryImpl implements VertigoDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static VertigoDslFactory init()
  {
    try
    {
      VertigoDslFactory theVertigoDslFactory = (VertigoDslFactory)EPackage.Registry.INSTANCE.getEFactory(VertigoDslPackage.eNS_URI);
      if (theVertigoDslFactory != null)
      {
        return theVertigoDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new VertigoDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VertigoDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case VertigoDslPackage.MODEL: return createModel();
      case VertigoDslPackage.PACKAGE_STRING: return createPackageString();
      case VertigoDslPackage.KEYWORDID: return createKEYWORDID();
      case VertigoDslPackage.ELEMENT: return createElement();
      case VertigoDslPackage.DECLARED_DOMAIN: return createDeclaredDomain();
      case VertigoDslPackage.DECLARED_DT_DEFINITION: return createDeclaredDtDefinition();
      case VertigoDslPackage.FILE_INFO: return createFileInfo();
      case VertigoDslPackage.DOMAIN: return createDomain();
      case VertigoDslPackage.ALTER_DOMAIN: return createAlterDomain();
      case VertigoDslPackage.DOMAIN_TYPE: return createDomainType();
      case VertigoDslPackage.REF_TO_DOMAIN_TYPE: return createRefToDomainType();
      case VertigoDslPackage.DT_DEFINITION_ID_STRING: return createDtDefinitionIdString();
      case VertigoDslPackage.DT_DEFINITION_DATA_FIELD_STRING: return createDtDefinitionDataFieldString();
      case VertigoDslPackage.DT_DEFINITION_COMPUTED_FIELD_STRING: return createDtDefinitionComputedFieldString();
      case VertigoDslPackage.DT_DEFINITION_ID_FIELD: return createDtDefinitionIdField();
      case VertigoDslPackage.DT_DEFINITION_DATA_FIELD: return createDtDefinitionDataField();
      case VertigoDslPackage.DT_DEFINITION_COMPUTED_FIELD: return createDtDefinitionComputedField();
      case VertigoDslPackage.DT_DEFINITION_STEREOTYPE: return createDtDefinitionStereotype();
      case VertigoDslPackage.DT_DEFINITION_DATA_SPACE: return createDtDefinitionDataSpace();
      case VertigoDslPackage.DT_DEFINITION_DISPLAY_FIELD: return createDtDefinitionDisplayField();
      case VertigoDslPackage.DT_DEFINITION_SORT_FIELD: return createDtDefinitionSortField();
      case VertigoDslPackage.DT_DEFINITION_HANDLE_FIELD: return createDtDefinitionHandleField();
      case VertigoDslPackage.DT_DEFINITION_STATIC_VALUES: return createDtDefinitionStaticValues();
      case VertigoDslPackage.DT_DEFINITION_TYPE: return createDtDefinitionType();
      case VertigoDslPackage.DT_DEFINITION: return createDtDefinition();
      case VertigoDslPackage.ALTER_DT_DEFINITION: return createAlterDtDefinition();
      case VertigoDslPackage.ASSOCIATION: return createAssociation();
      case VertigoDslPackage.TASK_ATTRIBUTE_STRING: return createTaskAttributeString();
      case VertigoDslPackage.TASK_IN_ATTRIBUTE: return createTaskInAttribute();
      case VertigoDslPackage.TASK_OUT_ATTRIBUTE: return createTaskOutAttribute();
      case VertigoDslPackage.TASK_DATA_SPACE: return createTaskDataSpace();
      case VertigoDslPackage.TASK_CLASS_NAME: return createTaskClassName();
      case VertigoDslPackage.TASK_REQUEST: return createTaskRequest();
      case VertigoDslPackage.TASK_REQUEST_STRING: return createTaskRequestString();
      case VertigoDslPackage.TASK_DEFINITION: return createTaskDefinition();
      case VertigoDslPackage.ALTER_TASK_DEFINITION: return createAlterTaskDefinition();
      case VertigoDslPackage.FACET_DEFINITION_DT_DEFINITION: return createFacetDefinitionDtDefinition();
      case VertigoDslPackage.FACET_DEFINITION_FIELD_NAME: return createFacetDefinitionFieldName();
      case VertigoDslPackage.FACET_DEFINITION_LABEL: return createFacetDefinitionLabel();
      case VertigoDslPackage.FACET_DEFINITION_RANGE_STRING: return createFacetDefinitionRangeString();
      case VertigoDslPackage.FACET_DEFINITION_RANGE: return createFacetDefinitionRange();
      case VertigoDslPackage.FACET_DEFINITION_PARAM_STRING: return createFacetDefinitionParamString();
      case VertigoDslPackage.FACET_DEFINITION_PARAM: return createFacetDefinitionParam();
      case VertigoDslPackage.FACET_DEFINITION: return createFacetDefinition();
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_KEY_CONCEPT: return createFacetedQueryDefinitionKeyConcept();
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_DOMAIN_CRITERIA: return createFacetedQueryDefinitionDomainCriteria();
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_LIST_FILTER_BUILDER_QUERY: return createFacetedQueryDefinitionListFilterBuilderQuery();
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_GEO_SEARCH_QUERY: return createFacetedQueryDefinitionGeoSearchQuery();
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_LIST_FILTER_BUILDER_CLASS: return createFacetedQueryDefinitionListFilterBuilderClass();
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_FACETS: return createFacetedQueryDefinitionFacets();
      case VertigoDslPackage.FACETED_QUERY_DEFINITION: return createFacetedQueryDefinition();
      case VertigoDslPackage.INDEX_DEFINITION_KEY_CONCEPT: return createIndexDefinitionKeyConcept();
      case VertigoDslPackage.INDEX_DEFINITION_DT_INDEX: return createIndexDefinitionDtIndex();
      case VertigoDslPackage.INDEX_DEFINITION_INDEX_COPY_TO_STRING: return createIndexDefinitionIndexCopyToString();
      case VertigoDslPackage.INDEX_DEFINITION_INDEX_COPY_TO: return createIndexDefinitionIndexCopyTo();
      case VertigoDslPackage.INDEX_DEFINITION_LOADER_ID: return createIndexDefinitionLoaderId();
      case VertigoDslPackage.INDEX_DEFINITION: return createIndexDefinition();
      case VertigoDslPackage.DT_DEFINITION_ACTION: return createDtDefinitionAction();
      case VertigoDslPackage.FACET_DEFINITION_ACTION: return createFacetDefinitionAction();
      case VertigoDslPackage.FACETED_QUERY_DEFINITION_ACTION: return createFacetedQueryDefinitionAction();
      case VertigoDslPackage.INDEX_DEFINITION_ACTION: return createIndexDefinitionAction();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case VertigoDslPackage.DATA_TYPE:
        return createDataTypeFromString(eDataType, initialValue);
      case VertigoDslPackage.BOOLEAN_STRING:
        return createBooleanStringFromString(eDataType, initialValue);
      case VertigoDslPackage.MULTIPLICITY_STRING:
        return createMultiplicityStringFromString(eDataType, initialValue);
      case VertigoDslPackage.CARDINALITY_STRING:
        return createCardinalityStringFromString(eDataType, initialValue);
      case VertigoDslPackage.ASSOCIATION_TYPE_STRING:
        return createAssociationTypeStringFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case VertigoDslPackage.DATA_TYPE:
        return convertDataTypeToString(eDataType, instanceValue);
      case VertigoDslPackage.BOOLEAN_STRING:
        return convertBooleanStringToString(eDataType, instanceValue);
      case VertigoDslPackage.MULTIPLICITY_STRING:
        return convertMultiplicityStringToString(eDataType, instanceValue);
      case VertigoDslPackage.CARDINALITY_STRING:
        return convertCardinalityStringToString(eDataType, instanceValue);
      case VertigoDslPackage.ASSOCIATION_TYPE_STRING:
        return convertAssociationTypeStringToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PackageString createPackageString()
  {
    PackageStringImpl packageString = new PackageStringImpl();
    return packageString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public KEYWORDID createKEYWORDID()
  {
    KEYWORDIDImpl keywordid = new KEYWORDIDImpl();
    return keywordid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Element createElement()
  {
    ElementImpl element = new ElementImpl();
    return element;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclaredDomain createDeclaredDomain()
  {
    DeclaredDomainImpl declaredDomain = new DeclaredDomainImpl();
    return declaredDomain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclaredDtDefinition createDeclaredDtDefinition()
  {
    DeclaredDtDefinitionImpl declaredDtDefinition = new DeclaredDtDefinitionImpl();
    return declaredDtDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FileInfo createFileInfo()
  {
    FileInfoImpl fileInfo = new FileInfoImpl();
    return fileInfo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Domain createDomain()
  {
    DomainImpl domain = new DomainImpl();
    return domain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AlterDomain createAlterDomain()
  {
    AlterDomainImpl alterDomain = new AlterDomainImpl();
    return alterDomain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DomainType createDomainType()
  {
    DomainTypeImpl domainType = new DomainTypeImpl();
    return domainType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RefToDomainType createRefToDomainType()
  {
    RefToDomainTypeImpl refToDomainType = new RefToDomainTypeImpl();
    return refToDomainType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionIdString createDtDefinitionIdString()
  {
    DtDefinitionIdStringImpl dtDefinitionIdString = new DtDefinitionIdStringImpl();
    return dtDefinitionIdString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionDataFieldString createDtDefinitionDataFieldString()
  {
    DtDefinitionDataFieldStringImpl dtDefinitionDataFieldString = new DtDefinitionDataFieldStringImpl();
    return dtDefinitionDataFieldString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionComputedFieldString createDtDefinitionComputedFieldString()
  {
    DtDefinitionComputedFieldStringImpl dtDefinitionComputedFieldString = new DtDefinitionComputedFieldStringImpl();
    return dtDefinitionComputedFieldString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionIdField createDtDefinitionIdField()
  {
    DtDefinitionIdFieldImpl dtDefinitionIdField = new DtDefinitionIdFieldImpl();
    return dtDefinitionIdField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionDataField createDtDefinitionDataField()
  {
    DtDefinitionDataFieldImpl dtDefinitionDataField = new DtDefinitionDataFieldImpl();
    return dtDefinitionDataField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionComputedField createDtDefinitionComputedField()
  {
    DtDefinitionComputedFieldImpl dtDefinitionComputedField = new DtDefinitionComputedFieldImpl();
    return dtDefinitionComputedField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionStereotype createDtDefinitionStereotype()
  {
    DtDefinitionStereotypeImpl dtDefinitionStereotype = new DtDefinitionStereotypeImpl();
    return dtDefinitionStereotype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionDataSpace createDtDefinitionDataSpace()
  {
    DtDefinitionDataSpaceImpl dtDefinitionDataSpace = new DtDefinitionDataSpaceImpl();
    return dtDefinitionDataSpace;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionDisplayField createDtDefinitionDisplayField()
  {
    DtDefinitionDisplayFieldImpl dtDefinitionDisplayField = new DtDefinitionDisplayFieldImpl();
    return dtDefinitionDisplayField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionSortField createDtDefinitionSortField()
  {
    DtDefinitionSortFieldImpl dtDefinitionSortField = new DtDefinitionSortFieldImpl();
    return dtDefinitionSortField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionHandleField createDtDefinitionHandleField()
  {
    DtDefinitionHandleFieldImpl dtDefinitionHandleField = new DtDefinitionHandleFieldImpl();
    return dtDefinitionHandleField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionStaticValues createDtDefinitionStaticValues()
  {
    DtDefinitionStaticValuesImpl dtDefinitionStaticValues = new DtDefinitionStaticValuesImpl();
    return dtDefinitionStaticValues;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionType createDtDefinitionType()
  {
    DtDefinitionTypeImpl dtDefinitionType = new DtDefinitionTypeImpl();
    return dtDefinitionType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinition createDtDefinition()
  {
    DtDefinitionImpl dtDefinition = new DtDefinitionImpl();
    return dtDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AlterDtDefinition createAlterDtDefinition()
  {
    AlterDtDefinitionImpl alterDtDefinition = new AlterDtDefinitionImpl();
    return alterDtDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Association createAssociation()
  {
    AssociationImpl association = new AssociationImpl();
    return association;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TaskAttributeString createTaskAttributeString()
  {
    TaskAttributeStringImpl taskAttributeString = new TaskAttributeStringImpl();
    return taskAttributeString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TaskInAttribute createTaskInAttribute()
  {
    TaskInAttributeImpl taskInAttribute = new TaskInAttributeImpl();
    return taskInAttribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TaskOutAttribute createTaskOutAttribute()
  {
    TaskOutAttributeImpl taskOutAttribute = new TaskOutAttributeImpl();
    return taskOutAttribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TaskDataSpace createTaskDataSpace()
  {
    TaskDataSpaceImpl taskDataSpace = new TaskDataSpaceImpl();
    return taskDataSpace;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TaskClassName createTaskClassName()
  {
    TaskClassNameImpl taskClassName = new TaskClassNameImpl();
    return taskClassName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TaskRequest createTaskRequest()
  {
    TaskRequestImpl taskRequest = new TaskRequestImpl();
    return taskRequest;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TaskRequestString createTaskRequestString()
  {
    TaskRequestStringImpl taskRequestString = new TaskRequestStringImpl();
    return taskRequestString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TaskDefinition createTaskDefinition()
  {
    TaskDefinitionImpl taskDefinition = new TaskDefinitionImpl();
    return taskDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AlterTaskDefinition createAlterTaskDefinition()
  {
    AlterTaskDefinitionImpl alterTaskDefinition = new AlterTaskDefinitionImpl();
    return alterTaskDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetDefinitionDtDefinition createFacetDefinitionDtDefinition()
  {
    FacetDefinitionDtDefinitionImpl facetDefinitionDtDefinition = new FacetDefinitionDtDefinitionImpl();
    return facetDefinitionDtDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetDefinitionFieldName createFacetDefinitionFieldName()
  {
    FacetDefinitionFieldNameImpl facetDefinitionFieldName = new FacetDefinitionFieldNameImpl();
    return facetDefinitionFieldName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetDefinitionLabel createFacetDefinitionLabel()
  {
    FacetDefinitionLabelImpl facetDefinitionLabel = new FacetDefinitionLabelImpl();
    return facetDefinitionLabel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetDefinitionRangeString createFacetDefinitionRangeString()
  {
    FacetDefinitionRangeStringImpl facetDefinitionRangeString = new FacetDefinitionRangeStringImpl();
    return facetDefinitionRangeString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetDefinitionRange createFacetDefinitionRange()
  {
    FacetDefinitionRangeImpl facetDefinitionRange = new FacetDefinitionRangeImpl();
    return facetDefinitionRange;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetDefinitionParamString createFacetDefinitionParamString()
  {
    FacetDefinitionParamStringImpl facetDefinitionParamString = new FacetDefinitionParamStringImpl();
    return facetDefinitionParamString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetDefinitionParam createFacetDefinitionParam()
  {
    FacetDefinitionParamImpl facetDefinitionParam = new FacetDefinitionParamImpl();
    return facetDefinitionParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetDefinition createFacetDefinition()
  {
    FacetDefinitionImpl facetDefinition = new FacetDefinitionImpl();
    return facetDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetedQueryDefinitionKeyConcept createFacetedQueryDefinitionKeyConcept()
  {
    FacetedQueryDefinitionKeyConceptImpl facetedQueryDefinitionKeyConcept = new FacetedQueryDefinitionKeyConceptImpl();
    return facetedQueryDefinitionKeyConcept;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetedQueryDefinitionDomainCriteria createFacetedQueryDefinitionDomainCriteria()
  {
    FacetedQueryDefinitionDomainCriteriaImpl facetedQueryDefinitionDomainCriteria = new FacetedQueryDefinitionDomainCriteriaImpl();
    return facetedQueryDefinitionDomainCriteria;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetedQueryDefinitionListFilterBuilderQuery createFacetedQueryDefinitionListFilterBuilderQuery()
  {
    FacetedQueryDefinitionListFilterBuilderQueryImpl facetedQueryDefinitionListFilterBuilderQuery = new FacetedQueryDefinitionListFilterBuilderQueryImpl();
    return facetedQueryDefinitionListFilterBuilderQuery;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetedQueryDefinitionGeoSearchQuery createFacetedQueryDefinitionGeoSearchQuery()
  {
    FacetedQueryDefinitionGeoSearchQueryImpl facetedQueryDefinitionGeoSearchQuery = new FacetedQueryDefinitionGeoSearchQueryImpl();
    return facetedQueryDefinitionGeoSearchQuery;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetedQueryDefinitionListFilterBuilderClass createFacetedQueryDefinitionListFilterBuilderClass()
  {
    FacetedQueryDefinitionListFilterBuilderClassImpl facetedQueryDefinitionListFilterBuilderClass = new FacetedQueryDefinitionListFilterBuilderClassImpl();
    return facetedQueryDefinitionListFilterBuilderClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetedQueryDefinitionFacets createFacetedQueryDefinitionFacets()
  {
    FacetedQueryDefinitionFacetsImpl facetedQueryDefinitionFacets = new FacetedQueryDefinitionFacetsImpl();
    return facetedQueryDefinitionFacets;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetedQueryDefinition createFacetedQueryDefinition()
  {
    FacetedQueryDefinitionImpl facetedQueryDefinition = new FacetedQueryDefinitionImpl();
    return facetedQueryDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IndexDefinitionKeyConcept createIndexDefinitionKeyConcept()
  {
    IndexDefinitionKeyConceptImpl indexDefinitionKeyConcept = new IndexDefinitionKeyConceptImpl();
    return indexDefinitionKeyConcept;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IndexDefinitionDtIndex createIndexDefinitionDtIndex()
  {
    IndexDefinitionDtIndexImpl indexDefinitionDtIndex = new IndexDefinitionDtIndexImpl();
    return indexDefinitionDtIndex;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IndexDefinitionIndexCopyToString createIndexDefinitionIndexCopyToString()
  {
    IndexDefinitionIndexCopyToStringImpl indexDefinitionIndexCopyToString = new IndexDefinitionIndexCopyToStringImpl();
    return indexDefinitionIndexCopyToString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IndexDefinitionIndexCopyTo createIndexDefinitionIndexCopyTo()
  {
    IndexDefinitionIndexCopyToImpl indexDefinitionIndexCopyTo = new IndexDefinitionIndexCopyToImpl();
    return indexDefinitionIndexCopyTo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IndexDefinitionLoaderId createIndexDefinitionLoaderId()
  {
    IndexDefinitionLoaderIdImpl indexDefinitionLoaderId = new IndexDefinitionLoaderIdImpl();
    return indexDefinitionLoaderId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IndexDefinition createIndexDefinition()
  {
    IndexDefinitionImpl indexDefinition = new IndexDefinitionImpl();
    return indexDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DtDefinitionAction createDtDefinitionAction()
  {
    DtDefinitionActionImpl dtDefinitionAction = new DtDefinitionActionImpl();
    return dtDefinitionAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetDefinitionAction createFacetDefinitionAction()
  {
    FacetDefinitionActionImpl facetDefinitionAction = new FacetDefinitionActionImpl();
    return facetDefinitionAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FacetedQueryDefinitionAction createFacetedQueryDefinitionAction()
  {
    FacetedQueryDefinitionActionImpl facetedQueryDefinitionAction = new FacetedQueryDefinitionActionImpl();
    return facetedQueryDefinitionAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IndexDefinitionAction createIndexDefinitionAction()
  {
    IndexDefinitionActionImpl indexDefinitionAction = new IndexDefinitionActionImpl();
    return indexDefinitionAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataType createDataTypeFromString(EDataType eDataType, String initialValue)
  {
    DataType result = DataType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertDataTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BooleanString createBooleanStringFromString(EDataType eDataType, String initialValue)
  {
    BooleanString result = BooleanString.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertBooleanStringToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MultiplicityString createMultiplicityStringFromString(EDataType eDataType, String initialValue)
  {
    MultiplicityString result = MultiplicityString.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertMultiplicityStringToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CardinalityString createCardinalityStringFromString(EDataType eDataType, String initialValue)
  {
    CardinalityString result = CardinalityString.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertCardinalityStringToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AssociationTypeString createAssociationTypeStringFromString(EDataType eDataType, String initialValue)
  {
    AssociationTypeString result = AssociationTypeString.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertAssociationTypeStringToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VertigoDslPackage getVertigoDslPackage()
  {
    return (VertigoDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static VertigoDslPackage getPackage()
  {
    return VertigoDslPackage.eINSTANCE;
  }

} //VertigoDslFactoryImpl
