/**
 * generated by Xtext 2.17.0
 */
package io.vertigo.dsl.vertigoDsl.impl;

import io.vertigo.dsl.vertigoDsl.Association;
import io.vertigo.dsl.vertigoDsl.BooleanString;
import io.vertigo.dsl.vertigoDsl.Constraint;
import io.vertigo.dsl.vertigoDsl.DataType;
import io.vertigo.dsl.vertigoDsl.DeclaredDomain;
import io.vertigo.dsl.vertigoDsl.DeclaredDtDefinition;
import io.vertigo.dsl.vertigoDsl.Domain;
import io.vertigo.dsl.vertigoDsl.DomainType;
import io.vertigo.dsl.vertigoDsl.DtDefinition;
import io.vertigo.dsl.vertigoDsl.DtDefinitionAction;
import io.vertigo.dsl.vertigoDsl.DtDefinitionComputedField;
import io.vertigo.dsl.vertigoDsl.DtDefinitionComputedFieldString;
import io.vertigo.dsl.vertigoDsl.DtDefinitionDataField;
import io.vertigo.dsl.vertigoDsl.DtDefinitionDataFieldString;
import io.vertigo.dsl.vertigoDsl.DtDefinitionDataSpace;
import io.vertigo.dsl.vertigoDsl.DtDefinitionDisplayField;
import io.vertigo.dsl.vertigoDsl.DtDefinitionIdField;
import io.vertigo.dsl.vertigoDsl.DtDefinitionIdString;
import io.vertigo.dsl.vertigoDsl.DtDefinitionSortField;
import io.vertigo.dsl.vertigoDsl.DtDefinitionStereotype;
import io.vertigo.dsl.vertigoDsl.DtDefinitionType;
import io.vertigo.dsl.vertigoDsl.Element;
import io.vertigo.dsl.vertigoDsl.FileInfo;
import io.vertigo.dsl.vertigoDsl.Formatter;
import io.vertigo.dsl.vertigoDsl.InOutString;
import io.vertigo.dsl.vertigoDsl.Model;
import io.vertigo.dsl.vertigoDsl.MultiplicityString;
import io.vertigo.dsl.vertigoDsl.PackageString;
import io.vertigo.dsl.vertigoDsl.RefToDomainType;
import io.vertigo.dsl.vertigoDsl.TaskAttribute;
import io.vertigo.dsl.vertigoDsl.TaskAttributeString;
import io.vertigo.dsl.vertigoDsl.TaskDataSpace;
import io.vertigo.dsl.vertigoDsl.TaskDefinition;
import io.vertigo.dsl.vertigoDsl.VertigoDslFactory;
import io.vertigo.dsl.vertigoDsl.VertigoDslPackage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class VertigoDslPackageImpl extends EPackageImpl implements VertigoDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass packageStringEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass keywordidEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declaredDomainEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declaredDtDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constraintEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fileInfoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass formatterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass domainEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass domainTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass refToDomainTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionIdStringEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionDataFieldStringEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionComputedFieldStringEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionIdFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionDataFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionComputedFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionStereotypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionDataSpaceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionDisplayFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionSortFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass associationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass taskAttributeStringEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass taskAttributeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass taskDataSpaceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass taskDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtDefinitionActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum dataTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum booleanStringEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum multiplicityStringEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum inOutStringEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private VertigoDslPackageImpl()
  {
    super(eNS_URI, VertigoDslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link VertigoDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static VertigoDslPackage init()
  {
    if (isInited) return (VertigoDslPackage)EPackage.Registry.INSTANCE.getEPackage(VertigoDslPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredVertigoDslPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    VertigoDslPackageImpl theVertigoDslPackage = registeredVertigoDslPackage instanceof VertigoDslPackageImpl ? (VertigoDslPackageImpl)registeredVertigoDslPackage : new VertigoDslPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theVertigoDslPackage.createPackageContents();

    // Initialize created meta-data
    theVertigoDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theVertigoDslPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(VertigoDslPackage.eNS_URI, theVertigoDslPackage);
    return theVertigoDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_PackageString()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Elements()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPackageString()
  {
    return packageStringEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPackageString_Package()
  {
    return (EReference)packageStringEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPackageString_Packages()
  {
    return (EReference)packageStringEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getKEYWORDID()
  {
    return keywordidEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getKEYWORDID_KeywordID()
  {
    return (EAttribute)keywordidEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getElement()
  {
    return elementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDeclaredDomain()
  {
    return declaredDomainEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDeclaredDomain_Name()
  {
    return (EAttribute)declaredDomainEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDeclaredDtDefinition()
  {
    return declaredDtDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDeclaredDtDefinition_Name()
  {
    return (EAttribute)declaredDtDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getConstraint()
  {
    return constraintEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getConstraint_Name()
  {
    return (EAttribute)constraintEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getConstraint_ClassName()
  {
    return (EAttribute)constraintEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getConstraint_Args()
  {
    return (EAttribute)constraintEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getConstraint_Msg()
  {
    return (EAttribute)constraintEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFileInfo()
  {
    return fileInfoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFileInfo_Name()
  {
    return (EAttribute)fileInfoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFileInfo_StoreName()
  {
    return (EAttribute)fileInfoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFormatter()
  {
    return formatterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFormatter_Name()
  {
    return (EAttribute)formatterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFormatter_ClassName()
  {
    return (EAttribute)formatterEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFormatter_Args()
  {
    return (EAttribute)formatterEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDomain()
  {
    return domainEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDomain_Name()
  {
    return (EAttribute)domainEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDomain_DataType()
  {
    return (EAttribute)domainEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDomain_Formatter()
  {
    return (EReference)domainEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDomain_StoreType()
  {
    return (EAttribute)domainEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDomain_IndexType()
  {
    return (EAttribute)domainEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDomain_Constraint()
  {
    return (EReference)domainEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDomain_Constraints()
  {
    return (EReference)domainEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDomain_Multiple()
  {
    return (EAttribute)domainEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDomain_Unit()
  {
    return (EAttribute)domainEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDomainType()
  {
    return domainTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRefToDomainType()
  {
    return refToDomainTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRefToDomainType_Ref()
  {
    return (EReference)refToDomainTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinitionIdString()
  {
    return dtDefinitionIdStringEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionIdString_RefToDomainType()
  {
    return (EReference)dtDefinitionIdStringEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionIdString_Label()
  {
    return (EAttribute)dtDefinitionIdStringEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinitionDataFieldString()
  {
    return dtDefinitionDataFieldStringEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionDataFieldString_RefToDomainType()
  {
    return (EReference)dtDefinitionDataFieldStringEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionDataFieldString_Label()
  {
    return (EAttribute)dtDefinitionDataFieldStringEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionDataFieldString_Required()
  {
    return (EAttribute)dtDefinitionDataFieldStringEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionDataFieldString_Persistent()
  {
    return (EAttribute)dtDefinitionDataFieldStringEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinitionComputedFieldString()
  {
    return dtDefinitionComputedFieldStringEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionComputedFieldString_RefToDomainType()
  {
    return (EReference)dtDefinitionComputedFieldStringEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionComputedFieldString_Label()
  {
    return (EAttribute)dtDefinitionComputedFieldStringEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionComputedFieldString_ExpressionString()
  {
    return (EAttribute)dtDefinitionComputedFieldStringEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinitionIdField()
  {
    return dtDefinitionIdFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionIdField_Name()
  {
    return (EAttribute)dtDefinitionIdFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionIdField_IdString()
  {
    return (EReference)dtDefinitionIdFieldEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinitionDataField()
  {
    return dtDefinitionDataFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionDataField_Name()
  {
    return (EAttribute)dtDefinitionDataFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionDataField_DataFieldString()
  {
    return (EReference)dtDefinitionDataFieldEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinitionComputedField()
  {
    return dtDefinitionComputedFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionComputedField_Name()
  {
    return (EAttribute)dtDefinitionComputedFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionComputedField_ComputedFieldString()
  {
    return (EReference)dtDefinitionComputedFieldEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinitionStereotype()
  {
    return dtDefinitionStereotypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionStereotype_StereoType()
  {
    return (EAttribute)dtDefinitionStereotypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinitionDataSpace()
  {
    return dtDefinitionDataSpaceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionDataSpace_StoreName()
  {
    return (EAttribute)dtDefinitionDataSpaceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinitionDisplayField()
  {
    return dtDefinitionDisplayFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionDisplayField_DisplayField()
  {
    return (EAttribute)dtDefinitionDisplayFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinitionSortField()
  {
    return dtDefinitionSortFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionSortField_SortField()
  {
    return (EAttribute)dtDefinitionSortFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinitionType()
  {
    return dtDefinitionTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinition()
  {
    return dtDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAssociation()
  {
    return associationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAssociation_Name()
  {
    return (EAttribute)associationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAssociation_FkFieldName()
  {
    return (EAttribute)associationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAssociation_DtDefinitionA()
  {
    return (EReference)associationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAssociation_DtDefinitionB()
  {
    return (EReference)associationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAssociation_NavigabilityA()
  {
    return (EAttribute)associationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAssociation_NavigabilityB()
  {
    return (EAttribute)associationEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAssociation_MultiplicityA()
  {
    return (EAttribute)associationEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAssociation_MultiplicityB()
  {
    return (EAttribute)associationEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAssociation_LabelA()
  {
    return (EAttribute)associationEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAssociation_LabelB()
  {
    return (EAttribute)associationEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAssociation_RoleA()
  {
    return (EAttribute)associationEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAssociation_RoleB()
  {
    return (EAttribute)associationEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAssociation_Type()
  {
    return (EAttribute)associationEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTaskAttributeString()
  {
    return taskAttributeStringEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTaskAttributeString_Domain()
  {
    return (EReference)taskAttributeStringEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTaskAttributeString_Required()
  {
    return (EAttribute)taskAttributeStringEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTaskAttributeString_Inout()
  {
    return (EAttribute)taskAttributeStringEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTaskAttribute()
  {
    return taskAttributeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTaskAttribute_Name()
  {
    return (EAttribute)taskAttributeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTaskAttribute_TaskAttributeString()
  {
    return (EReference)taskAttributeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTaskDataSpace()
  {
    return taskDataSpaceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTaskDataSpace_StoreName()
  {
    return (EAttribute)taskDataSpaceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTaskDefinition()
  {
    return taskDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTaskDefinition_Name()
  {
    return (EAttribute)taskDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTaskDefinition_Classname()
  {
    return (EAttribute)taskDefinitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTaskDefinition_Request()
  {
    return (EAttribute)taskDefinitionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTaskDefinition_TaskAttributes()
  {
    return (EReference)taskDefinitionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTaskDefinition_TaskDataSpace()
  {
    return (EReference)taskDefinitionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtDefinitionAction()
  {
    return dtDefinitionActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDtDefinitionAction_Name()
  {
    return (EAttribute)dtDefinitionActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionAction_DtDefinitionStereotype()
  {
    return (EReference)dtDefinitionActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionAction_DtDefinitionIdField()
  {
    return (EReference)dtDefinitionActionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionAction_DtDefinitionDataFields()
  {
    return (EReference)dtDefinitionActionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionAction_DtDefinitionComputedFields()
  {
    return (EReference)dtDefinitionActionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionAction_DtDefinitionDataSpace()
  {
    return (EReference)dtDefinitionActionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionAction_DtDefinitionSortField()
  {
    return (EReference)dtDefinitionActionEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtDefinitionAction_DtDefinitionDisplayField()
  {
    return (EReference)dtDefinitionActionEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getDataType()
  {
    return dataTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getBooleanString()
  {
    return booleanStringEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getMultiplicityString()
  {
    return multiplicityStringEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getInOutString()
  {
    return inOutStringEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VertigoDslFactory getVertigoDslFactory()
  {
    return (VertigoDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__PACKAGE_STRING);
    createEReference(modelEClass, MODEL__ELEMENTS);

    packageStringEClass = createEClass(PACKAGE_STRING);
    createEReference(packageStringEClass, PACKAGE_STRING__PACKAGE);
    createEReference(packageStringEClass, PACKAGE_STRING__PACKAGES);

    keywordidEClass = createEClass(KEYWORDID);
    createEAttribute(keywordidEClass, KEYWORDID__KEYWORD_ID);

    elementEClass = createEClass(ELEMENT);

    declaredDomainEClass = createEClass(DECLARED_DOMAIN);
    createEAttribute(declaredDomainEClass, DECLARED_DOMAIN__NAME);

    declaredDtDefinitionEClass = createEClass(DECLARED_DT_DEFINITION);
    createEAttribute(declaredDtDefinitionEClass, DECLARED_DT_DEFINITION__NAME);

    constraintEClass = createEClass(CONSTRAINT);
    createEAttribute(constraintEClass, CONSTRAINT__NAME);
    createEAttribute(constraintEClass, CONSTRAINT__CLASS_NAME);
    createEAttribute(constraintEClass, CONSTRAINT__ARGS);
    createEAttribute(constraintEClass, CONSTRAINT__MSG);

    fileInfoEClass = createEClass(FILE_INFO);
    createEAttribute(fileInfoEClass, FILE_INFO__NAME);
    createEAttribute(fileInfoEClass, FILE_INFO__STORE_NAME);

    formatterEClass = createEClass(FORMATTER);
    createEAttribute(formatterEClass, FORMATTER__NAME);
    createEAttribute(formatterEClass, FORMATTER__CLASS_NAME);
    createEAttribute(formatterEClass, FORMATTER__ARGS);

    domainEClass = createEClass(DOMAIN);
    createEAttribute(domainEClass, DOMAIN__NAME);
    createEAttribute(domainEClass, DOMAIN__DATA_TYPE);
    createEReference(domainEClass, DOMAIN__FORMATTER);
    createEAttribute(domainEClass, DOMAIN__STORE_TYPE);
    createEAttribute(domainEClass, DOMAIN__INDEX_TYPE);
    createEReference(domainEClass, DOMAIN__CONSTRAINT);
    createEReference(domainEClass, DOMAIN__CONSTRAINTS);
    createEAttribute(domainEClass, DOMAIN__MULTIPLE);
    createEAttribute(domainEClass, DOMAIN__UNIT);

    domainTypeEClass = createEClass(DOMAIN_TYPE);

    refToDomainTypeEClass = createEClass(REF_TO_DOMAIN_TYPE);
    createEReference(refToDomainTypeEClass, REF_TO_DOMAIN_TYPE__REF);

    dtDefinitionIdStringEClass = createEClass(DT_DEFINITION_ID_STRING);
    createEReference(dtDefinitionIdStringEClass, DT_DEFINITION_ID_STRING__REF_TO_DOMAIN_TYPE);
    createEAttribute(dtDefinitionIdStringEClass, DT_DEFINITION_ID_STRING__LABEL);

    dtDefinitionDataFieldStringEClass = createEClass(DT_DEFINITION_DATA_FIELD_STRING);
    createEReference(dtDefinitionDataFieldStringEClass, DT_DEFINITION_DATA_FIELD_STRING__REF_TO_DOMAIN_TYPE);
    createEAttribute(dtDefinitionDataFieldStringEClass, DT_DEFINITION_DATA_FIELD_STRING__LABEL);
    createEAttribute(dtDefinitionDataFieldStringEClass, DT_DEFINITION_DATA_FIELD_STRING__REQUIRED);
    createEAttribute(dtDefinitionDataFieldStringEClass, DT_DEFINITION_DATA_FIELD_STRING__PERSISTENT);

    dtDefinitionComputedFieldStringEClass = createEClass(DT_DEFINITION_COMPUTED_FIELD_STRING);
    createEReference(dtDefinitionComputedFieldStringEClass, DT_DEFINITION_COMPUTED_FIELD_STRING__REF_TO_DOMAIN_TYPE);
    createEAttribute(dtDefinitionComputedFieldStringEClass, DT_DEFINITION_COMPUTED_FIELD_STRING__LABEL);
    createEAttribute(dtDefinitionComputedFieldStringEClass, DT_DEFINITION_COMPUTED_FIELD_STRING__EXPRESSION_STRING);

    dtDefinitionIdFieldEClass = createEClass(DT_DEFINITION_ID_FIELD);
    createEAttribute(dtDefinitionIdFieldEClass, DT_DEFINITION_ID_FIELD__NAME);
    createEReference(dtDefinitionIdFieldEClass, DT_DEFINITION_ID_FIELD__ID_STRING);

    dtDefinitionDataFieldEClass = createEClass(DT_DEFINITION_DATA_FIELD);
    createEAttribute(dtDefinitionDataFieldEClass, DT_DEFINITION_DATA_FIELD__NAME);
    createEReference(dtDefinitionDataFieldEClass, DT_DEFINITION_DATA_FIELD__DATA_FIELD_STRING);

    dtDefinitionComputedFieldEClass = createEClass(DT_DEFINITION_COMPUTED_FIELD);
    createEAttribute(dtDefinitionComputedFieldEClass, DT_DEFINITION_COMPUTED_FIELD__NAME);
    createEReference(dtDefinitionComputedFieldEClass, DT_DEFINITION_COMPUTED_FIELD__COMPUTED_FIELD_STRING);

    dtDefinitionStereotypeEClass = createEClass(DT_DEFINITION_STEREOTYPE);
    createEAttribute(dtDefinitionStereotypeEClass, DT_DEFINITION_STEREOTYPE__STEREO_TYPE);

    dtDefinitionDataSpaceEClass = createEClass(DT_DEFINITION_DATA_SPACE);
    createEAttribute(dtDefinitionDataSpaceEClass, DT_DEFINITION_DATA_SPACE__STORE_NAME);

    dtDefinitionDisplayFieldEClass = createEClass(DT_DEFINITION_DISPLAY_FIELD);
    createEAttribute(dtDefinitionDisplayFieldEClass, DT_DEFINITION_DISPLAY_FIELD__DISPLAY_FIELD);

    dtDefinitionSortFieldEClass = createEClass(DT_DEFINITION_SORT_FIELD);
    createEAttribute(dtDefinitionSortFieldEClass, DT_DEFINITION_SORT_FIELD__SORT_FIELD);

    dtDefinitionTypeEClass = createEClass(DT_DEFINITION_TYPE);

    dtDefinitionEClass = createEClass(DT_DEFINITION);

    associationEClass = createEClass(ASSOCIATION);
    createEAttribute(associationEClass, ASSOCIATION__NAME);
    createEAttribute(associationEClass, ASSOCIATION__FK_FIELD_NAME);
    createEReference(associationEClass, ASSOCIATION__DT_DEFINITION_A);
    createEReference(associationEClass, ASSOCIATION__DT_DEFINITION_B);
    createEAttribute(associationEClass, ASSOCIATION__NAVIGABILITY_A);
    createEAttribute(associationEClass, ASSOCIATION__NAVIGABILITY_B);
    createEAttribute(associationEClass, ASSOCIATION__MULTIPLICITY_A);
    createEAttribute(associationEClass, ASSOCIATION__MULTIPLICITY_B);
    createEAttribute(associationEClass, ASSOCIATION__LABEL_A);
    createEAttribute(associationEClass, ASSOCIATION__LABEL_B);
    createEAttribute(associationEClass, ASSOCIATION__ROLE_A);
    createEAttribute(associationEClass, ASSOCIATION__ROLE_B);
    createEAttribute(associationEClass, ASSOCIATION__TYPE);

    taskAttributeStringEClass = createEClass(TASK_ATTRIBUTE_STRING);
    createEReference(taskAttributeStringEClass, TASK_ATTRIBUTE_STRING__DOMAIN);
    createEAttribute(taskAttributeStringEClass, TASK_ATTRIBUTE_STRING__REQUIRED);
    createEAttribute(taskAttributeStringEClass, TASK_ATTRIBUTE_STRING__INOUT);

    taskAttributeEClass = createEClass(TASK_ATTRIBUTE);
    createEAttribute(taskAttributeEClass, TASK_ATTRIBUTE__NAME);
    createEReference(taskAttributeEClass, TASK_ATTRIBUTE__TASK_ATTRIBUTE_STRING);

    taskDataSpaceEClass = createEClass(TASK_DATA_SPACE);
    createEAttribute(taskDataSpaceEClass, TASK_DATA_SPACE__STORE_NAME);

    taskDefinitionEClass = createEClass(TASK_DEFINITION);
    createEAttribute(taskDefinitionEClass, TASK_DEFINITION__NAME);
    createEAttribute(taskDefinitionEClass, TASK_DEFINITION__CLASSNAME);
    createEAttribute(taskDefinitionEClass, TASK_DEFINITION__REQUEST);
    createEReference(taskDefinitionEClass, TASK_DEFINITION__TASK_ATTRIBUTES);
    createEReference(taskDefinitionEClass, TASK_DEFINITION__TASK_DATA_SPACE);

    dtDefinitionActionEClass = createEClass(DT_DEFINITION_ACTION);
    createEAttribute(dtDefinitionActionEClass, DT_DEFINITION_ACTION__NAME);
    createEReference(dtDefinitionActionEClass, DT_DEFINITION_ACTION__DT_DEFINITION_STEREOTYPE);
    createEReference(dtDefinitionActionEClass, DT_DEFINITION_ACTION__DT_DEFINITION_ID_FIELD);
    createEReference(dtDefinitionActionEClass, DT_DEFINITION_ACTION__DT_DEFINITION_DATA_FIELDS);
    createEReference(dtDefinitionActionEClass, DT_DEFINITION_ACTION__DT_DEFINITION_COMPUTED_FIELDS);
    createEReference(dtDefinitionActionEClass, DT_DEFINITION_ACTION__DT_DEFINITION_DATA_SPACE);
    createEReference(dtDefinitionActionEClass, DT_DEFINITION_ACTION__DT_DEFINITION_SORT_FIELD);
    createEReference(dtDefinitionActionEClass, DT_DEFINITION_ACTION__DT_DEFINITION_DISPLAY_FIELD);

    // Create enums
    dataTypeEEnum = createEEnum(DATA_TYPE);
    booleanStringEEnum = createEEnum(BOOLEAN_STRING);
    multiplicityStringEEnum = createEEnum(MULTIPLICITY_STRING);
    inOutStringEEnum = createEEnum(IN_OUT_STRING);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    declaredDomainEClass.getESuperTypes().add(this.getElement());
    declaredDomainEClass.getESuperTypes().add(this.getDomainType());
    declaredDtDefinitionEClass.getESuperTypes().add(this.getElement());
    declaredDtDefinitionEClass.getESuperTypes().add(this.getDtDefinitionType());
    constraintEClass.getESuperTypes().add(this.getElement());
    fileInfoEClass.getESuperTypes().add(this.getElement());
    formatterEClass.getESuperTypes().add(this.getElement());
    domainEClass.getESuperTypes().add(this.getElement());
    domainEClass.getESuperTypes().add(this.getDomainType());
    dtDefinitionEClass.getESuperTypes().add(this.getElement());
    dtDefinitionEClass.getESuperTypes().add(this.getDtDefinitionType());
    associationEClass.getESuperTypes().add(this.getElement());
    taskDefinitionEClass.getESuperTypes().add(this.getElement());
    dtDefinitionActionEClass.getESuperTypes().add(this.getDtDefinition());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_PackageString(), this.getPackageString(), null, "packageString", null, 0, 1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Elements(), this.getElement(), null, "elements", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(packageStringEClass, PackageString.class, "PackageString", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPackageString_Package(), this.getKEYWORDID(), null, "package", null, 0, -1, PackageString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPackageString_Packages(), this.getKEYWORDID(), null, "packages", null, 0, -1, PackageString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(keywordidEClass, io.vertigo.dsl.vertigoDsl.KEYWORDID.class, "KEYWORDID", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getKEYWORDID_KeywordID(), ecorePackage.getEString(), "keywordID", null, 0, 1, io.vertigo.dsl.vertigoDsl.KEYWORDID.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(elementEClass, Element.class, "Element", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(declaredDomainEClass, DeclaredDomain.class, "DeclaredDomain", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDeclaredDomain_Name(), ecorePackage.getEString(), "name", null, 0, 1, DeclaredDomain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declaredDtDefinitionEClass, DeclaredDtDefinition.class, "DeclaredDtDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDeclaredDtDefinition_Name(), ecorePackage.getEString(), "name", null, 0, 1, DeclaredDtDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constraintEClass, Constraint.class, "Constraint", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConstraint_Name(), ecorePackage.getEString(), "name", null, 0, 1, Constraint.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getConstraint_ClassName(), ecorePackage.getEString(), "className", null, 0, 1, Constraint.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getConstraint_Args(), ecorePackage.getEString(), "args", null, 0, 1, Constraint.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getConstraint_Msg(), ecorePackage.getEString(), "msg", null, 0, 1, Constraint.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fileInfoEClass, FileInfo.class, "FileInfo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFileInfo_Name(), ecorePackage.getEString(), "name", null, 0, 1, FileInfo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFileInfo_StoreName(), ecorePackage.getEString(), "storeName", null, 0, 1, FileInfo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(formatterEClass, Formatter.class, "Formatter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFormatter_Name(), ecorePackage.getEString(), "name", null, 0, 1, Formatter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFormatter_ClassName(), ecorePackage.getEString(), "className", null, 0, 1, Formatter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFormatter_Args(), ecorePackage.getEString(), "args", null, 0, 1, Formatter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(domainEClass, Domain.class, "Domain", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDomain_Name(), ecorePackage.getEString(), "name", null, 0, 1, Domain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDomain_DataType(), this.getDataType(), "dataType", null, 0, 1, Domain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDomain_Formatter(), this.getFormatter(), null, "formatter", null, 0, 1, Domain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDomain_StoreType(), ecorePackage.getEString(), "storeType", null, 0, 1, Domain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDomain_IndexType(), ecorePackage.getEString(), "indexType", null, 0, 1, Domain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDomain_Constraint(), this.getConstraint(), null, "constraint", null, 0, -1, Domain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDomain_Constraints(), this.getConstraint(), null, "constraints", null, 0, -1, Domain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDomain_Multiple(), this.getBooleanString(), "multiple", null, 0, 1, Domain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDomain_Unit(), ecorePackage.getEString(), "unit", null, 0, 1, Domain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(domainTypeEClass, DomainType.class, "DomainType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(refToDomainTypeEClass, RefToDomainType.class, "RefToDomainType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRefToDomainType_Ref(), this.getDomainType(), null, "ref", null, 0, 1, RefToDomainType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtDefinitionIdStringEClass, DtDefinitionIdString.class, "DtDefinitionIdString", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDtDefinitionIdString_RefToDomainType(), this.getRefToDomainType(), null, "refToDomainType", null, 0, 1, DtDefinitionIdString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDtDefinitionIdString_Label(), ecorePackage.getEString(), "label", null, 0, 1, DtDefinitionIdString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtDefinitionDataFieldStringEClass, DtDefinitionDataFieldString.class, "DtDefinitionDataFieldString", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDtDefinitionDataFieldString_RefToDomainType(), this.getRefToDomainType(), null, "refToDomainType", null, 0, 1, DtDefinitionDataFieldString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDtDefinitionDataFieldString_Label(), ecorePackage.getEString(), "label", null, 0, 1, DtDefinitionDataFieldString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDtDefinitionDataFieldString_Required(), this.getBooleanString(), "required", null, 0, 1, DtDefinitionDataFieldString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDtDefinitionDataFieldString_Persistent(), this.getBooleanString(), "persistent", null, 0, 1, DtDefinitionDataFieldString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtDefinitionComputedFieldStringEClass, DtDefinitionComputedFieldString.class, "DtDefinitionComputedFieldString", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDtDefinitionComputedFieldString_RefToDomainType(), this.getRefToDomainType(), null, "refToDomainType", null, 0, 1, DtDefinitionComputedFieldString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDtDefinitionComputedFieldString_Label(), ecorePackage.getEString(), "label", null, 0, 1, DtDefinitionComputedFieldString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDtDefinitionComputedFieldString_ExpressionString(), ecorePackage.getEString(), "expressionString", null, 0, 1, DtDefinitionComputedFieldString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtDefinitionIdFieldEClass, DtDefinitionIdField.class, "DtDefinitionIdField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDtDefinitionIdField_Name(), ecorePackage.getEString(), "name", null, 0, 1, DtDefinitionIdField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtDefinitionIdField_IdString(), this.getDtDefinitionIdString(), null, "idString", null, 0, 1, DtDefinitionIdField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtDefinitionDataFieldEClass, DtDefinitionDataField.class, "DtDefinitionDataField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDtDefinitionDataField_Name(), ecorePackage.getEString(), "name", null, 0, 1, DtDefinitionDataField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtDefinitionDataField_DataFieldString(), this.getDtDefinitionDataFieldString(), null, "dataFieldString", null, 0, 1, DtDefinitionDataField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtDefinitionComputedFieldEClass, DtDefinitionComputedField.class, "DtDefinitionComputedField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDtDefinitionComputedField_Name(), ecorePackage.getEString(), "name", null, 0, 1, DtDefinitionComputedField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtDefinitionComputedField_ComputedFieldString(), this.getDtDefinitionComputedFieldString(), null, "computedFieldString", null, 0, 1, DtDefinitionComputedField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtDefinitionStereotypeEClass, DtDefinitionStereotype.class, "DtDefinitionStereotype", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDtDefinitionStereotype_StereoType(), ecorePackage.getEString(), "stereoType", null, 0, 1, DtDefinitionStereotype.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtDefinitionDataSpaceEClass, DtDefinitionDataSpace.class, "DtDefinitionDataSpace", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDtDefinitionDataSpace_StoreName(), ecorePackage.getEString(), "storeName", null, 0, 1, DtDefinitionDataSpace.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtDefinitionDisplayFieldEClass, DtDefinitionDisplayField.class, "DtDefinitionDisplayField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDtDefinitionDisplayField_DisplayField(), ecorePackage.getEString(), "displayField", null, 0, 1, DtDefinitionDisplayField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtDefinitionSortFieldEClass, DtDefinitionSortField.class, "DtDefinitionSortField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDtDefinitionSortField_SortField(), ecorePackage.getEString(), "sortField", null, 0, 1, DtDefinitionSortField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtDefinitionTypeEClass, DtDefinitionType.class, "DtDefinitionType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(dtDefinitionEClass, DtDefinition.class, "DtDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(associationEClass, Association.class, "Association", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAssociation_Name(), ecorePackage.getEString(), "name", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAssociation_FkFieldName(), ecorePackage.getEString(), "fkFieldName", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAssociation_DtDefinitionA(), this.getDtDefinitionType(), null, "dtDefinitionA", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAssociation_DtDefinitionB(), this.getDtDefinitionType(), null, "dtDefinitionB", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAssociation_NavigabilityA(), this.getBooleanString(), "navigabilityA", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAssociation_NavigabilityB(), this.getBooleanString(), "navigabilityB", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAssociation_MultiplicityA(), this.getMultiplicityString(), "multiplicityA", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAssociation_MultiplicityB(), this.getMultiplicityString(), "multiplicityB", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAssociation_LabelA(), ecorePackage.getEString(), "labelA", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAssociation_LabelB(), ecorePackage.getEString(), "labelB", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAssociation_RoleA(), ecorePackage.getEString(), "roleA", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAssociation_RoleB(), ecorePackage.getEString(), "roleB", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAssociation_Type(), ecorePackage.getEString(), "type", null, 0, 1, Association.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(taskAttributeStringEClass, TaskAttributeString.class, "TaskAttributeString", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTaskAttributeString_Domain(), this.getDomainType(), null, "domain", null, 0, 1, TaskAttributeString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTaskAttributeString_Required(), this.getBooleanString(), "required", null, 0, 1, TaskAttributeString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTaskAttributeString_Inout(), this.getInOutString(), "inout", null, 0, 1, TaskAttributeString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(taskAttributeEClass, TaskAttribute.class, "TaskAttribute", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTaskAttribute_Name(), ecorePackage.getEString(), "name", null, 0, 1, TaskAttribute.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTaskAttribute_TaskAttributeString(), this.getTaskAttributeString(), null, "taskAttributeString", null, 0, 1, TaskAttribute.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(taskDataSpaceEClass, TaskDataSpace.class, "TaskDataSpace", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTaskDataSpace_StoreName(), ecorePackage.getEString(), "storeName", null, 0, 1, TaskDataSpace.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(taskDefinitionEClass, TaskDefinition.class, "TaskDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTaskDefinition_Name(), ecorePackage.getEString(), "name", null, 0, 1, TaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTaskDefinition_Classname(), ecorePackage.getEString(), "classname", null, 0, 1, TaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTaskDefinition_Request(), ecorePackage.getEString(), "request", null, 0, 1, TaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTaskDefinition_TaskAttributes(), this.getTaskAttribute(), null, "taskAttributes", null, 0, -1, TaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTaskDefinition_TaskDataSpace(), this.getTaskDataSpace(), null, "taskDataSpace", null, 0, 1, TaskDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtDefinitionActionEClass, DtDefinitionAction.class, "DtDefinitionAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDtDefinitionAction_Name(), ecorePackage.getEString(), "name", null, 0, 1, DtDefinitionAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtDefinitionAction_DtDefinitionStereotype(), this.getDtDefinitionStereotype(), null, "dtDefinitionStereotype", null, 0, 1, DtDefinitionAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtDefinitionAction_DtDefinitionIdField(), this.getDtDefinitionIdField(), null, "dtDefinitionIdField", null, 0, 1, DtDefinitionAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtDefinitionAction_DtDefinitionDataFields(), this.getDtDefinitionDataField(), null, "dtDefinitionDataFields", null, 0, -1, DtDefinitionAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtDefinitionAction_DtDefinitionComputedFields(), this.getDtDefinitionComputedField(), null, "dtDefinitionComputedFields", null, 0, -1, DtDefinitionAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtDefinitionAction_DtDefinitionDataSpace(), this.getDtDefinitionDataSpace(), null, "dtDefinitionDataSpace", null, 0, 1, DtDefinitionAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtDefinitionAction_DtDefinitionSortField(), this.getDtDefinitionSortField(), null, "dtDefinitionSortField", null, 0, 1, DtDefinitionAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDtDefinitionAction_DtDefinitionDisplayField(), this.getDtDefinitionDisplayField(), null, "dtDefinitionDisplayField", null, 0, 1, DtDefinitionAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(dataTypeEEnum, DataType.class, "DataType");
    addEEnumLiteral(dataTypeEEnum, DataType.INTEGER);
    addEEnumLiteral(dataTypeEEnum, DataType.DOUBLE);
    addEEnumLiteral(dataTypeEEnum, DataType.BOOLEAN);
    addEEnumLiteral(dataTypeEEnum, DataType.STRING);
    addEEnumLiteral(dataTypeEEnum, DataType.LOCAL_DATE);
    addEEnumLiteral(dataTypeEEnum, DataType.INSTANT);
    addEEnumLiteral(dataTypeEEnum, DataType.BIG_DECIMAL);
    addEEnumLiteral(dataTypeEEnum, DataType.LONG);
    addEEnumLiteral(dataTypeEEnum, DataType.DATA_STREAM);

    initEEnum(booleanStringEEnum, BooleanString.class, "BooleanString");
    addEEnumLiteral(booleanStringEEnum, BooleanString.TRUE);
    addEEnumLiteral(booleanStringEEnum, BooleanString.FALSE);

    initEEnum(multiplicityStringEEnum, MultiplicityString.class, "MultiplicityString");
    addEEnumLiteral(multiplicityStringEEnum, MultiplicityString.ZERO_ONE);
    addEEnumLiteral(multiplicityStringEEnum, MultiplicityString.ZERO_N);

    initEEnum(inOutStringEEnum, InOutString.class, "InOutString");
    addEEnumLiteral(inOutStringEEnum, InOutString.INOUT_IN);
    addEEnumLiteral(inOutStringEEnum, InOutString.INOUT_OUT);

    // Create resource
    createResource(eNS_URI);
  }

} //VertigoDslPackageImpl
