/*
 * generated by Xtext 2.17.0
 */
package io.vertigo.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractVertigoDslScopeProvider extends DelegatingScopeProvider {
}
