source.. = src/,\
           icons/,\
           src-gen/,\
           xtend-gen/
bin.includes = .,\
               icons/,\
               META-INF/,\
               plugin.xml
bin.excludes = **/*.xtend
