/**
 * generated by Xtext 2.21.0
 */
package io.vertigo.dsl.scoping;

import io.vertigo.dsl.scoping.AbstractVertigoDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class VertigoDslScopeProvider extends AbstractVertigoDslScopeProvider {
}
