/**
 * generated by Xtext 2.17.1
 */
package io.vertigo.dsl.vertigoDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declared Dt Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.DeclaredDtDefinition#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getDeclaredDtDefinition()
 * @model
 * @generated
 */
public interface DeclaredDtDefinition extends Element, DtDefinitionType
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getDeclaredDtDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.vertigo.dsl.vertigoDsl.DeclaredDtDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // DeclaredDtDefinition
