/**
 * generated by Xtext 2.17.0
 */
package io.vertigo.dsl.vertigoDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declared Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getDeclaredDomain()
 * @model
 * @generated
 */
public interface DeclaredDomain extends Element, DomainType
{
} // DeclaredDomain
