/**
 * generated by Xtext 2.18.0
 */
package io.vertigo.dsl.vertigoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Domain Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getDomainType()
 * @model
 * @generated
 */
public interface DomainType extends EObject
{
} // DomainType
