/**
 * generated by Xtext 2.21.0
 */
package io.vertigo.dsl.vertigoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dt Definition Handle Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.DtDefinitionHandleField#getHandleField <em>Handle Field</em>}</li>
 * </ul>
 *
 * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getDtDefinitionHandleField()
 * @model
 * @generated
 */
public interface DtDefinitionHandleField extends EObject
{
  /**
   * Returns the value of the '<em><b>Handle Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Handle Field</em>' attribute.
   * @see #setHandleField(String)
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getDtDefinitionHandleField_HandleField()
   * @model
   * @generated
   */
  String getHandleField();

  /**
   * Sets the value of the '{@link io.vertigo.dsl.vertigoDsl.DtDefinitionHandleField#getHandleField <em>Handle Field</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Handle Field</em>' attribute.
   * @see #getHandleField()
   * @generated
   */
  void setHandleField(String value);

} // DtDefinitionHandleField
