/**
 * generated by Xtext 2.23.0
 */
package io.vertigo.dsl.vertigoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
} // Element
