/**
 * generated by Xtext 2.21.0
 */
package io.vertigo.dsl.vertigoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Faceted Query Definition Key Concept</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.FacetedQueryDefinitionKeyConcept#getDtDefinition <em>Dt Definition</em>}</li>
 * </ul>
 *
 * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getFacetedQueryDefinitionKeyConcept()
 * @model
 * @generated
 */
public interface FacetedQueryDefinitionKeyConcept extends EObject
{
  /**
   * Returns the value of the '<em><b>Dt Definition</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dt Definition</em>' reference.
   * @see #setDtDefinition(DtDefinitionType)
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getFacetedQueryDefinitionKeyConcept_DtDefinition()
   * @model
   * @generated
   */
  DtDefinitionType getDtDefinition();

  /**
   * Sets the value of the '{@link io.vertigo.dsl.vertigoDsl.FacetedQueryDefinitionKeyConcept#getDtDefinition <em>Dt Definition</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dt Definition</em>' reference.
   * @see #getDtDefinition()
   * @generated
   */
  void setDtDefinition(DtDefinitionType value);

} // FacetedQueryDefinitionKeyConcept
