/**
 * generated by Xtext 2.21.0
 */
package io.vertigo.dsl.vertigoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Facet Definition Param String</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.FacetDefinitionParamString#getParamValueString <em>Param Value String</em>}</li>
 * </ul>
 *
 * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getFacetDefinitionParamString()
 * @model
 * @generated
 */
public interface FacetDefinitionParamString extends EObject
{
  /**
   * Returns the value of the '<em><b>Param Value String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Value String</em>' attribute.
   * @see #setParamValueString(String)
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getFacetDefinitionParamString_ParamValueString()
   * @model
   * @generated
   */
  String getParamValueString();

  /**
   * Sets the value of the '{@link io.vertigo.dsl.vertigoDsl.FacetDefinitionParamString#getParamValueString <em>Param Value String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param Value String</em>' attribute.
   * @see #getParamValueString()
   * @generated
   */
  void setParamValueString(String value);

} // FacetDefinitionParamString
