/**
 * generated by Xtext 2.21.0
 */
package io.vertigo.dsl.vertigoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Facet Definition Range String</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.FacetDefinitionRangeString#getFilterString <em>Filter String</em>}</li>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.FacetDefinitionRangeString#getLabelString <em>Label String</em>}</li>
 * </ul>
 *
 * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getFacetDefinitionRangeString()
 * @model
 * @generated
 */
public interface FacetDefinitionRangeString extends EObject
{
  /**
   * Returns the value of the '<em><b>Filter String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter String</em>' attribute.
   * @see #setFilterString(String)
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getFacetDefinitionRangeString_FilterString()
   * @model
   * @generated
   */
  String getFilterString();

  /**
   * Sets the value of the '{@link io.vertigo.dsl.vertigoDsl.FacetDefinitionRangeString#getFilterString <em>Filter String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter String</em>' attribute.
   * @see #getFilterString()
   * @generated
   */
  void setFilterString(String value);

  /**
   * Returns the value of the '<em><b>Label String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label String</em>' attribute.
   * @see #setLabelString(String)
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getFacetDefinitionRangeString_LabelString()
   * @model
   * @generated
   */
  String getLabelString();

  /**
   * Sets the value of the '{@link io.vertigo.dsl.vertigoDsl.FacetDefinitionRangeString#getLabelString <em>Label String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label String</em>' attribute.
   * @see #getLabelString()
   * @generated
   */
  void setLabelString(String value);

} // FacetDefinitionRangeString
