/**
 * generated by Xtext 2.17.0
 */
package io.vertigo.dsl.vertigoDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.Model#getPackage <em>Package</em>}</li>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.Model#getPackages <em>Packages</em>}</li>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.Model#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Package</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Package</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Package</em>' attribute list.
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getModel_Package()
   * @model unique="false"
   * @generated
   */
  EList<String> getPackage();

  /**
   * Returns the value of the '<em><b>Packages</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Packages</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Packages</em>' attribute list.
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getModel_Packages()
   * @model unique="false"
   * @generated
   */
  EList<String> getPackages();

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link io.vertigo.dsl.vertigoDsl.Element}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getModel_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElements();

} // Model
