/**
 * generated by Xtext 2.18.0
 */
package io.vertigo.dsl.vertigoDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.TaskDefinition#getName <em>Name</em>}</li>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.TaskDefinition#getClassname <em>Classname</em>}</li>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.TaskDefinition#getRequest <em>Request</em>}</li>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.TaskDefinition#getTaskAttributes <em>Task Attributes</em>}</li>
 *   <li>{@link io.vertigo.dsl.vertigoDsl.TaskDefinition#getTaskDataSpace <em>Task Data Space</em>}</li>
 * </ul>
 *
 * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getTaskDefinition()
 * @model
 * @generated
 */
public interface TaskDefinition extends Element
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getTaskDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.vertigo.dsl.vertigoDsl.TaskDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Classname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classname</em>' attribute.
   * @see #setClassname(String)
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getTaskDefinition_Classname()
   * @model
   * @generated
   */
  String getClassname();

  /**
   * Sets the value of the '{@link io.vertigo.dsl.vertigoDsl.TaskDefinition#getClassname <em>Classname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Classname</em>' attribute.
   * @see #getClassname()
   * @generated
   */
  void setClassname(String value);

  /**
   * Returns the value of the '<em><b>Request</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Request</em>' containment reference.
   * @see #setRequest(TaskRequestString)
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getTaskDefinition_Request()
   * @model containment="true"
   * @generated
   */
  TaskRequestString getRequest();

  /**
   * Sets the value of the '{@link io.vertigo.dsl.vertigoDsl.TaskDefinition#getRequest <em>Request</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Request</em>' containment reference.
   * @see #getRequest()
   * @generated
   */
  void setRequest(TaskRequestString value);

  /**
   * Returns the value of the '<em><b>Task Attributes</b></em>' containment reference list.
   * The list contents are of type {@link io.vertigo.dsl.vertigoDsl.TaskAttribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Task Attributes</em>' containment reference list.
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getTaskDefinition_TaskAttributes()
   * @model containment="true"
   * @generated
   */
  EList<TaskAttribute> getTaskAttributes();

  /**
   * Returns the value of the '<em><b>Task Data Space</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Task Data Space</em>' containment reference.
   * @see #setTaskDataSpace(TaskDataSpace)
   * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage#getTaskDefinition_TaskDataSpace()
   * @model containment="true"
   * @generated
   */
  TaskDataSpace getTaskDataSpace();

  /**
   * Sets the value of the '{@link io.vertigo.dsl.vertigoDsl.TaskDefinition#getTaskDataSpace <em>Task Data Space</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Task Data Space</em>' containment reference.
   * @see #getTaskDataSpace()
   * @generated
   */
  void setTaskDataSpace(TaskDataSpace value);

} // TaskDefinition
