/**
 * generated by Xtext 2.17.0
 */
package io.vertigo.dsl.vertigoDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see io.vertigo.dsl.vertigoDsl.VertigoDslPackage
 * @generated
 */
public interface VertigoDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VertigoDslFactory eINSTANCE = io.vertigo.dsl.vertigoDsl.impl.VertigoDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Package String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Package String</em>'.
   * @generated
   */
  PackageString createPackageString();

  /**
   * Returns a new object of class '<em>KEYWORDID</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>KEYWORDID</em>'.
   * @generated
   */
  KEYWORDID createKEYWORDID();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  Element createElement();

  /**
   * Returns a new object of class '<em>Declared Domain</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declared Domain</em>'.
   * @generated
   */
  DeclaredDomain createDeclaredDomain();

  /**
   * Returns a new object of class '<em>Declared Dt Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declared Dt Definition</em>'.
   * @generated
   */
  DeclaredDtDefinition createDeclaredDtDefinition();

  /**
   * Returns a new object of class '<em>Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint</em>'.
   * @generated
   */
  Constraint createConstraint();

  /**
   * Returns a new object of class '<em>File Info</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>File Info</em>'.
   * @generated
   */
  FileInfo createFileInfo();

  /**
   * Returns a new object of class '<em>Formatter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Formatter</em>'.
   * @generated
   */
  Formatter createFormatter();

  /**
   * Returns a new object of class '<em>Domain</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Domain</em>'.
   * @generated
   */
  Domain createDomain();

  /**
   * Returns a new object of class '<em>Domain Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Domain Type</em>'.
   * @generated
   */
  DomainType createDomainType();

  /**
   * Returns a new object of class '<em>Ref To Domain Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ref To Domain Type</em>'.
   * @generated
   */
  RefToDomainType createRefToDomainType();

  /**
   * Returns a new object of class '<em>Dt Definition Id String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition Id String</em>'.
   * @generated
   */
  DtDefinitionIdString createDtDefinitionIdString();

  /**
   * Returns a new object of class '<em>Dt Definition Data Field String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition Data Field String</em>'.
   * @generated
   */
  DtDefinitionDataFieldString createDtDefinitionDataFieldString();

  /**
   * Returns a new object of class '<em>Dt Definition Computed Field String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition Computed Field String</em>'.
   * @generated
   */
  DtDefinitionComputedFieldString createDtDefinitionComputedFieldString();

  /**
   * Returns a new object of class '<em>Dt Definition Id Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition Id Field</em>'.
   * @generated
   */
  DtDefinitionIdField createDtDefinitionIdField();

  /**
   * Returns a new object of class '<em>Dt Definition Data Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition Data Field</em>'.
   * @generated
   */
  DtDefinitionDataField createDtDefinitionDataField();

  /**
   * Returns a new object of class '<em>Dt Definition Computed Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition Computed Field</em>'.
   * @generated
   */
  DtDefinitionComputedField createDtDefinitionComputedField();

  /**
   * Returns a new object of class '<em>Dt Definition Stereotype</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition Stereotype</em>'.
   * @generated
   */
  DtDefinitionStereotype createDtDefinitionStereotype();

  /**
   * Returns a new object of class '<em>Dt Definition Data Space</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition Data Space</em>'.
   * @generated
   */
  DtDefinitionDataSpace createDtDefinitionDataSpace();

  /**
   * Returns a new object of class '<em>Dt Definition Display Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition Display Field</em>'.
   * @generated
   */
  DtDefinitionDisplayField createDtDefinitionDisplayField();

  /**
   * Returns a new object of class '<em>Dt Definition Sort Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition Sort Field</em>'.
   * @generated
   */
  DtDefinitionSortField createDtDefinitionSortField();

  /**
   * Returns a new object of class '<em>Dt Definition Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition Type</em>'.
   * @generated
   */
  DtDefinitionType createDtDefinitionType();

  /**
   * Returns a new object of class '<em>Dt Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition</em>'.
   * @generated
   */
  DtDefinition createDtDefinition();

  /**
   * Returns a new object of class '<em>Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Association</em>'.
   * @generated
   */
  Association createAssociation();

  /**
   * Returns a new object of class '<em>Task Attribute String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task Attribute String</em>'.
   * @generated
   */
  TaskAttributeString createTaskAttributeString();

  /**
   * Returns a new object of class '<em>Task Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task Attribute</em>'.
   * @generated
   */
  TaskAttribute createTaskAttribute();

  /**
   * Returns a new object of class '<em>Task Data Space</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task Data Space</em>'.
   * @generated
   */
  TaskDataSpace createTaskDataSpace();

  /**
   * Returns a new object of class '<em>Task Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task Definition</em>'.
   * @generated
   */
  TaskDefinition createTaskDefinition();

  /**
   * Returns a new object of class '<em>Dt Definition Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dt Definition Action</em>'.
   * @generated
   */
  DtDefinitionAction createDtDefinitionAction();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  VertigoDslPackage getVertigoDslPackage();

} //VertigoDslFactory
