/*
 * generated by Xtext 2.17.0
 */
package io.vertigo.dsl.serializer;

import com.google.inject.Inject;
import io.vertigo.dsl.services.VertigoDslGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class VertigoDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected VertigoDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Domain_CommaKeyword_4_4_0_p;
	protected AbstractElementAlias match_Domain_RightCurlyBracketKeyword_7_a;
	protected AbstractElementAlias match_Domain_RightCurlyBracketKeyword_7_p;
	protected AbstractElementAlias match_Model_FullStopKeyword_2_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (VertigoDslGrammarAccess) access;
		match_Domain_CommaKeyword_4_4_0_p = new TokenAlias(true, false, grammarAccess.getDomainAccess().getCommaKeyword_4_4_0());
		match_Domain_RightCurlyBracketKeyword_7_a = new TokenAlias(true, true, grammarAccess.getDomainAccess().getRightCurlyBracketKeyword_7());
		match_Domain_RightCurlyBracketKeyword_7_p = new TokenAlias(true, false, grammarAccess.getDomainAccess().getRightCurlyBracketKeyword_7());
		match_Model_FullStopKeyword_2_0_p = new TokenAlias(true, false, grammarAccess.getModelAccess().getFullStopKeyword_2_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Domain_CommaKeyword_4_4_0_p.equals(syntax))
				emit_Domain_CommaKeyword_4_4_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Domain_RightCurlyBracketKeyword_7_a.equals(syntax))
				emit_Domain_RightCurlyBracketKeyword_7_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Domain_RightCurlyBracketKeyword_7_p.equals(syntax))
				emit_Domain_RightCurlyBracketKeyword_7_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Model_FullStopKeyword_2_0_p.equals(syntax))
				emit_Model_FullStopKeyword_2_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ','+
	 *
	 * This ambiguous syntax occurs at:
	 *     constraint+=[Constraint|ID] (ambiguity) constraints+=[Constraint|ID]
	 *     constraints+=[Constraint|ID] (ambiguity) constraints+=[Constraint|ID]
	 */
	protected void emit_Domain_CommaKeyword_4_4_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '}'*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'constraint' ':' '[' constraint+=[Constraint|ID]
	 *     (rule start) (ambiguity) 'create' 'Domain' name=ID
	 *     (rule start) (ambiguity) 'formatter' ':' formatter=[Formatter|ID]
	 *     (rule start) (ambiguity) 'indexType' ':' indexType=STRING
	 *     (rule start) (ambiguity) 'multiple' ':' multiple=BooleanString
	 *     (rule start) (ambiguity) 'storeType' ':' storeType=STRING
	 *     (rule start) (ambiguity) 'unit' ':' unit=STRING
	 *     (rule start) (ambiguity) (rule start)
	 *     constraint+=[Constraint|ID] ']' (ambiguity) 'constraint' ':' '[' constraint+=[Constraint|ID]
	 *     constraint+=[Constraint|ID] ']' (ambiguity) 'create' 'Domain' name=ID
	 *     constraint+=[Constraint|ID] ']' (ambiguity) 'formatter' ':' formatter=[Formatter|ID]
	 *     constraint+=[Constraint|ID] ']' (ambiguity) 'indexType' ':' indexType=STRING
	 *     constraint+=[Constraint|ID] ']' (ambiguity) 'multiple' ':' multiple=BooleanString
	 *     constraint+=[Constraint|ID] ']' (ambiguity) 'storeType' ':' storeType=STRING
	 *     constraint+=[Constraint|ID] ']' (ambiguity) 'unit' ':' unit=STRING
	 *     constraint+=[Constraint|ID] ']' (ambiguity) (rule end)
	 *     constraints+=[Constraint|ID] ']' (ambiguity) 'constraint' ':' '[' constraint+=[Constraint|ID]
	 *     constraints+=[Constraint|ID] ']' (ambiguity) 'create' 'Domain' name=ID
	 *     constraints+=[Constraint|ID] ']' (ambiguity) 'formatter' ':' formatter=[Formatter|ID]
	 *     constraints+=[Constraint|ID] ']' (ambiguity) 'indexType' ':' indexType=STRING
	 *     constraints+=[Constraint|ID] ']' (ambiguity) 'multiple' ':' multiple=BooleanString
	 *     constraints+=[Constraint|ID] ']' (ambiguity) 'storeType' ':' storeType=STRING
	 *     constraints+=[Constraint|ID] ']' (ambiguity) 'unit' ':' unit=STRING
	 *     constraints+=[Constraint|ID] ']' (ambiguity) (rule end)
	 *     dataType=DataType (ambiguity) 'constraint' ':' '[' constraint+=[Constraint|ID]
	 *     dataType=DataType (ambiguity) 'create' 'Domain' name=ID
	 *     dataType=DataType (ambiguity) 'formatter' ':' formatter=[Formatter|ID]
	 *     dataType=DataType (ambiguity) 'indexType' ':' indexType=STRING
	 *     dataType=DataType (ambiguity) 'multiple' ':' multiple=BooleanString
	 *     dataType=DataType (ambiguity) 'storeType' ':' storeType=STRING
	 *     dataType=DataType (ambiguity) 'unit' ':' unit=STRING
	 *     dataType=DataType (ambiguity) (rule end)
	 *     formatter=[Formatter|ID] (ambiguity) 'constraint' ':' '[' constraint+=[Constraint|ID]
	 *     formatter=[Formatter|ID] (ambiguity) 'create' 'Domain' name=ID
	 *     formatter=[Formatter|ID] (ambiguity) 'formatter' ':' formatter=[Formatter|ID]
	 *     formatter=[Formatter|ID] (ambiguity) 'indexType' ':' indexType=STRING
	 *     formatter=[Formatter|ID] (ambiguity) 'multiple' ':' multiple=BooleanString
	 *     formatter=[Formatter|ID] (ambiguity) 'storeType' ':' storeType=STRING
	 *     formatter=[Formatter|ID] (ambiguity) 'unit' ':' unit=STRING
	 *     formatter=[Formatter|ID] (ambiguity) (rule end)
	 *     indexType=STRING (ambiguity) 'constraint' ':' '[' constraint+=[Constraint|ID]
	 *     indexType=STRING (ambiguity) 'create' 'Domain' name=ID
	 *     indexType=STRING (ambiguity) 'formatter' ':' formatter=[Formatter|ID]
	 *     indexType=STRING (ambiguity) 'indexType' ':' indexType=STRING
	 *     indexType=STRING (ambiguity) 'multiple' ':' multiple=BooleanString
	 *     indexType=STRING (ambiguity) 'storeType' ':' storeType=STRING
	 *     indexType=STRING (ambiguity) 'unit' ':' unit=STRING
	 *     indexType=STRING (ambiguity) (rule end)
	 *     multiple=BooleanString (ambiguity) 'constraint' ':' '[' constraint+=[Constraint|ID]
	 *     multiple=BooleanString (ambiguity) 'create' 'Domain' name=ID
	 *     multiple=BooleanString (ambiguity) 'formatter' ':' formatter=[Formatter|ID]
	 *     multiple=BooleanString (ambiguity) 'indexType' ':' indexType=STRING
	 *     multiple=BooleanString (ambiguity) 'multiple' ':' multiple=BooleanString
	 *     multiple=BooleanString (ambiguity) 'storeType' ':' storeType=STRING
	 *     multiple=BooleanString (ambiguity) 'unit' ':' unit=STRING
	 *     multiple=BooleanString (ambiguity) (rule end)
	 *     storeType=STRING (ambiguity) 'constraint' ':' '[' constraint+=[Constraint|ID]
	 *     storeType=STRING (ambiguity) 'create' 'Domain' name=ID
	 *     storeType=STRING (ambiguity) 'formatter' ':' formatter=[Formatter|ID]
	 *     storeType=STRING (ambiguity) 'indexType' ':' indexType=STRING
	 *     storeType=STRING (ambiguity) 'multiple' ':' multiple=BooleanString
	 *     storeType=STRING (ambiguity) 'storeType' ':' storeType=STRING
	 *     storeType=STRING (ambiguity) 'unit' ':' unit=STRING
	 *     storeType=STRING (ambiguity) (rule end)
	 *     unit=STRING (ambiguity) 'constraint' ':' '[' constraint+=[Constraint|ID]
	 *     unit=STRING (ambiguity) 'create' 'Domain' name=ID
	 *     unit=STRING (ambiguity) 'formatter' ':' formatter=[Formatter|ID]
	 *     unit=STRING (ambiguity) 'indexType' ':' indexType=STRING
	 *     unit=STRING (ambiguity) 'multiple' ':' multiple=BooleanString
	 *     unit=STRING (ambiguity) 'storeType' ':' storeType=STRING
	 *     unit=STRING (ambiguity) 'unit' ':' unit=STRING
	 *     unit=STRING (ambiguity) (rule end)
	 */
	protected void emit_Domain_RightCurlyBracketKeyword_7_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '}'+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_Domain_RightCurlyBracketKeyword_7_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '.'+
	 *
	 * This ambiguous syntax occurs at:
	 *     package+=ID (ambiguity) packages+=ID
	 *     packages+=ID (ambiguity) packages+=ID
	 */
	protected void emit_Model_FullStopKeyword_2_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
